[workspace]

members = [
    "chapter_4",
    "chapter_5",
    "chapter_6",
    "chapter_7/a_standard_binary",
    "chapter_7/b_standard_library",
    "chapter_7/c_multiple_crates",
    "chapter_7/d_custom_crate_files",
]
